---
- name: Deploy Catalogue (Node.js 18)
  hosts: catalogue
  become: yes
  gather_facts: yes

  vars:
    app_user: roboshop
    app_dir: /app
    service_name: catalogue
    artifact_url: https://roboshop-builds.s3.amazonaws.com/catalogue.zip
    artifact_path: /tmp/catalogue.zip

    pre_tasks:
    - name: Reset Node.js module if supported
      ansible.builtin.command: dnf -y module reset nodejs
      register: reset_result
      failed_when: reset_result.rc != 0 and ("No such command: module" not in (reset_result.stderr | default('') + reset_result.stdout | default('')))
      changed_when: "'Nothing to do' not in (reset_result.stdout | default('') + reset_result.stderr | default(''))"
      when: ansible_facts.pkg_mgr == 'dnf'

    - name: Enable Node.js 18 module if supported
      ansible.builtin.command: dnf -y module enable nodejs:18
      register: enable_result
      failed_when: enable_result.rc != 0 and ("No such command: module" not in (enable_result.stderr | default('') + enable_result.stdout | default('')))
      changed_when: "'Nothing to do' not in (enable_result.stdout | default('') + enable_result.stderr | default(''))"
      when: ansible_facts.pkg_mgr == 'dnf'


  tasks:
    - name: Install Node.js
      ansible.builtin.dnf:
        name: nodejs
        state: present

    - name: Create application user
      ansible.builtin.user:
        name: "{{ app_user }}"
        system: yes
        create_home: no

    - name: Create application directory
      ansible.builtin.file:
        path: "{{ app_dir }}"
        state: directory
        owner: "{{ app_user }}"
        group: "{{ app_user }}"
        mode: "0755"

    - name: Download catalogue application
      ansible.builtin.get_url:
        url: "{{ artifact_url }}"
        dest: "{{ artifact_path }}"
        mode: "0644"
        force: yes

    - name: Extract catalogue application
      ansible.builtin.unarchive:
        src: "{{ artifact_path }}"
        dest: "{{ app_dir }}"
        remote_src: yes
        owner: "{{ app_user }}"
        group: "{{ app_user }}"

    - name: Install Node dependencies
      ansible.builtin.command: npm install --omit=dev
      args:
        chdir: "{{ app_dir }}"
        creates: "{{ app_dir }}/node_modules"
      become_user: "{{ app_user }}"

    - name: Install systemd unit
      ansible.builtin.copy:
        src: catalogue.service
        dest: "/etc/systemd/system/{{ service_name }}.service"
        mode: "0644"
      notify:
        - Reload systemd
        - Restart catalogue

    - name: Ensure service is enabled and started
      ansible.builtin.systemd:
        name: "{{ service_name }}"
        enabled: yes
        state: started

    - name: Place MongoDB YUM repo file (for mongo shell)
      ansible.builtin.copy:
        src: mongodb.repo
        dest: /etc/yum.repos.d/mongodb.repo
        mode: "0644"

    - name: Install MongoDB client
      ansible.builtin.dnf:
        name: mongodb-org-shell
        state: present

  handlers:
    - name: Reload systemd
      ansible.builtin.systemd:
        daemon_reload: true

    - name: Restart catalogue
      ansible.builtin.systemd:
        name: "{{ service_name }}"
        state: restarted
