---
- name: Install & configure MongoDB
  hosts: mongodb
  become: yes
  gather_facts: yes

  tasks:
    - name: Place MongoDB YUM repo file
      ansible.builtin.copy:
        src: mongodb.repo                 # keep this next to the playbook or in files/
        dest: /etc/yum.repos.d/mongodb.repo
        mode: "0644"

    - name: Install MongoDB
      ansible.builtin.package:
        name: mongodb-org
        state: present

    - name: Ensure mongod is enabled and started
      ansible.builtin.service:
        name: mongod
        state: started
        enabled: yes

    - name: Allow remote connections (bind to all interfaces)
      ansible.builtin.lineinfile:
        path: /etc/mongod.conf
        regexp: '^(\s*)bindIp:\s*.*$'
        line: '\1bindIp: 0.0.0.0'
        backrefs: yes
      notify: Restart mongod

  handlers:
    - name: Restart mongod
      ansible.builtin.service:
        name: mongod
        state: restarted
